### ISSUE TITLE
Not enough space for wikixray.py

### ISSUE THREAD

**Issue by wuwenzhen** [ticcky/esalib#8]
when running scripts/wikixray.py pages-articles.xml ,I got  the following error
Traceback (most recent call last):
  File "G:/esalib/scripts/wikixray.py", line 509, in <module>
    filter_handler.parse(sys.stdin)
  File "J:\python64\lib\xml\sax\saxutils.py", line 283, in parse
    self._parent.parse(source)
  File "J:\python64\lib\xml\sax\expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "J:\python64\lib\xml\sax\xmlreader.py", line 121, in parse
    buffer = file.read(self._bufsize)
IOError: [Errno 12] Not enough space

it means need more memory space?

Thanks

**Comment by ticcky** [comment]
The problem is perhaps the space on your hard-drive.
